import React from 'react'



function Conditions() {
    
    return (
        <div>
           <p>Conditions d'utilisation
  
  Les présentes modalités et conditions (les « conditions d'utilisation ») définissent la relation entre vous, le Groupe TMX Limitée (le « Groupe TMX ») et ses sociétés affiliées et ses filiales, y compris, le cas échéant, TSX Inc., Bourse de croissance TSX Inc., Bourse de Montréal Inc., La Caisse canadienne de dépôt de valeurs limitée, la Corporation canadienne de compensation de produits dérivés, Shorcan Brokers Limited, Alpha Trading Systems Inc. et Compagnie Trust TSX (collectivement « TMX » ou « nous ») quant à l'utilisation des sites TMX.com et/ou Money.TMX.com, situés respectivement aux adresses www.tmx.com et money.tmx.com/fr (collectivement « les sites Web »). En naviguant sur ces sites Web, vous acceptez de vous conformer aux conditions d'utilisation et d'y être lié légalement. Si ces conditions d'utilisation ne vous sont pas acceptables, veuillez ne pas naviguer sur ces sites.
  
  De temps à autre, il se peut que nous mettions à jour ces conditions d'utilisation; il vous appartient d'examiner régulièrement la plus récente version actualisée des sites Web. En continuant d'utiliser ces sites Web, vous serez réputé en avoir accepté les plus récentes conditions d'utilisation.
  
  Dans ces conditions d'utilisation, l'expression « fournisseurs de services » englobe, sans s'y limiter, les donneurs de licence, vendeurs, fournisseurs d'information ou autres tierces parties qui fournissent, à l'occasion, des données, de l'information, du contenu, des applications, des outils, des caractéristiques ou d'autres services pour les besoins des sites Web. Dans ces conditions d'utilisation, l'expression « fournisseurs de services » inclut, mais ne se limite pas à, tout détenteur de licence, vendeur, fournisseur d'information, ou toute autre tierce partie qui fournit, à l'occasion, des données, du contenu, des applications, des outils, des caractéristiques ou autres services aux fins des sites Web.
  
  Droits et restrictions d'utilisation
  TMX vous accorde une licence limitée non exclusive et non transférable vous permettant de visualiser et d'imprimer les renseignements publiés sur les sites Web, et ce, uniquement à des fins non commerciales ou personnelles. Toute copie effectuée doit conserver tous les avis de droits d'auteur et autres avis figurant sur ces sites Web. Sous réserve des dispositions énoncées à la phrase précédente, vous ne pouvez utiliser, distribuer, vendre, modifier, transmettre, réviser, décompiler, rééditer, afficher ou créer des dérivés (le cas échéant) des marques de commerce, des appellations commerciales, des logos, des designs, des agencements, des renseignements, des données, des logiciels, des applications, des caractéristiques interactives, des outils, des services ou du contenu disponibles sur les sites Web (désignés ci-après par l'expression « contenu » des sites Web), sans avoir préalablement obtenu l'autorisation écrite de TMX. Vous convenez et reconnaissez que les sites Web et leur contenu sont la propriété de TMX, de ses affiliées et fournisseurs de services et que vous n'acquerrez pas de droits ni de licences relatifs aux marques de commerce, brevets, droits d'auteur ou autre propriété intellectuelle dans les sites Web ou leur contenu. Les sites Web et leur contenu sont protégés par droits d'auteur, à la fois à titre de création individuelle et à titre d'œuvre collective. Ils sont aussi protégés par les lois sur les marques de commerce et les brevets, de même que par d'autres lois applicables.
  
  Renseignements sur le marché
  L'ensemble des renseignements sur le marché et des autres données, y compris, mais ne se limitant pas aux cotes, renseignements sur les sociétés, graphiques, nouvelles, options et données de recherche, sont fournis par TMX et ses fournisseurs de services à titre d'information seulement et ne sont pas destinés à des fins de négociation. TMX, ainsi que ses fournisseurs de services ne garantissent pas la séquence, l'exactitude et l'exhaustivité de toute information de marché ou d'autres données affichées, et ne sont pas imputables ni responsables d'aucune façon de tout délai, de toute inexactitude ou de toute erreur dans toute information de marché ou d'autres données affichées ou encore de la transmission de toute information de marché ou d'autres données affichées. Vous acceptez de ne pas vous fier à l'information de marché ni à d'autres données affichées pour des besoins commerciaux, financiers ou transactionnels et TMX, ses fournisseurs de services et chacune de leurs sociétés affiliées, dirigeants, administrateurs et mandataires respectifs ne sont imputables ni responsables d'aucune façon pour tous dommages, pertes ou coûts subis du fait de l'utilisation de ces données ou de la non-exécution, de l'interruption ou de la cessation pour quelque raison que ce soit du service d'affichage de l'information de marché ou d'autres données.
  
  Les titres faisant l'objet de réserves d'usage ne sont pas des titres inscrits et n'ont pas été émis. Des dispositions contractuelles spéciales s'appliquent. S'il n'y a pas de clôture, ces transactions seront annulées.
  
  Les renseignements sur le marché sont généralement décalés de 15 minutes ou plus. Veuillez vérifier l'heure et la date correspondantes dans chaque graphique ou tableau de données de marché pour connaître la temporalité des données. Avant d'acheter ou de vendre des titres ou d'autres produits financiers, vous devriez toujours consulter un courtier qualifié ou tout autre conseiller financier qualifié afin de vérifier les renseignements sur les cours.
  
  Veuillez tenir compte des avertissements supplémentaires et des conditions et restrictions d'utilisation affichées sur les pages individuelles des sites Web, y compris les attributions au fournisseur de services et les conditions d'utilisation indiquées au bas de chacune des pages de renseignements de marché des sites Web, car votre utilisation de ces pages est assujettie à ces conditions supplémentaires et il vous incombe de vous conformer à celles-ci.
  
  Autorisation d'utiliser les sites Web
  En naviguant sur les sites Web, vous nous signifiez que vous avez le pouvoir et l'autorité de conclure une entente avec nous et d'accepter les présentes conditions d'utilisation, que vous êtes apte à assumer et que vous assumez tout risque lié à l'utilisation des sites Web et de leur contenu, et que vous comprenez et acceptez les modalités, les conditions et les risques liés à l'utilisation des sites Web et de leur contenu. Si vous n'êtes pas satisfait des sites Web et de leur contenu, la seule mesure que vous pouvez prendre consiste exclusivement à cesser de les utiliser.
  
  Avis de non-responsabilité
  Le contenu des sites Web ou rendu disponible au moyen des sites Web vous est présenté uniquement à titre d'information et n'est pas présenté dans l'intention de donner des conseils juridiques, comptables, fiscaux, de placement, financiers ou autre, et il ne faut pas se fier à ce connu pour de tels conseils. TMX, ses fournisseurs de services et chacun de leurs affiliés, dirigeants, administrateurs, mandataires et mandataires respectifs n'assument aucune responsabilité à l'égard de renseignements inexacts, différés ou incomplets, ou pour toute action entreprise parce que l'on s'est fié à ces renseignements. Le contenu des sites Web ou rendu disponible au moyen des sites Web, y compris celui obtenu des fournisseurs de services ou de tout autre site lié, a été fourni par ces fournisseurs de services ou autres tierces parties sans vérification de notre part. Les points de vue, opinions et conseils de tierces parties disponibles sur les sites Web ne reflètent que l'avis de leurs auteurs et ne sont pas cautionnés par nous. Le rendement passé n'est pas nécessairement indicatif du rendement futur. Avant de prendre toute décision de placement, il est recommandé de consulter directement la personne ou l'entreprise et de recueillir l'avis d'un conseiller en placement compétent. Ni TMX, ni aucune de ses affiliées ou aucun des fournisseurs de services ne formulent ou n'ont formulé de recommandations quant aux titres ou aux services de placement d'une personne ou d'une entité relativement au contenu des sites Web, ou aux avantages pour un particulier d'investir dans les titres en général.
  
  BIEN QUE LE CONTENU AIT ÉTÉ OBTENU AUPRÈS DE SOURCES TENUES POUR FIABLES, LES SITES WEB ET LEUR CONTENU POURRAIENT COMPRENDRE DES INEXACTITUDES TECHNIQUES OU D'AUTRES INEXACTITUDES OU DES INEXACTITUDES TYPOGRAPHIQUES ET LES INFORMATIONS VOUS SONT FOURNIES « TELLES QUELLES », ET SANS AUCUNE GARANTIE NI AUTRE REPRÉSENTATION DE QUELQUE NATURE QUE CE SOIT. TMX, SES AFFILIÉES ET FOURNISSEURS DE SERVICES NE FONT AUCUNE DÉCLARATION ET NIENT TOUTE GARANTIE ET CONDITION, IMPLICITE ET EXPRESSE, DE QUELQUE NATURE QUE CE SOIT, Y COMPRIS ET SANS S'Y LIMITER, LES DÉCLARATIONS, GARANTIES OU CONDITIONS RELATIVES À L'EXACTITUDE, À LA PONCTUALITÉ, À L'EXHAUSTIVITÉ, À LA NON-VIOLATION, À LA QUALITÉ SATISFAISANTE, À L'ATTRAIT COMMERCIAL, À LA QUALITÉ MARCHANDE OU À L'APPLICABILITÉ À TOUT USAGE PARTICULIER AINSI QU'À TOUTES CELLES DÉCOULANT DE LA LOI, DE STATUTS, D'USAGES COMMERCIAUX OU DU COURS DE NÉGOCIATIONS. TMX, SES AFFILIÉES ET FOURNISSEURS DE SERVICES N'ASSUMENT AUCUNE RESPONSABILITÉ À VOTRE ÉGARD OU À CELUI DE TOUTE TIERCE PARTIE RELATIVEMENT AUX CONSÉQUENCES DE TOUTE ERREUR OU OMISSION.
  
  La méthodologie VIX est la propriété de Chicago Board Options Exchange (« CBOE »). CBOE a accordé à S&P Dow Jones Indices LLC (« S&P ») une licence lui permettant d'utiliser la méthodologie VIX pour créer l'indice S&P/TSX 60 VIX et a accepté que S&P puisse diffuser les valeurs de l'indice S&P/TSX 60 VIX. Ni CBOE, ni S&P, ni TSX Inc. (« TSX ») ou leurs affiliées respectives ne font de déclarations à l'égard de cet indice ou quant à la pertinence de se fier à cet indice pour quelque motif que ce soit. Ni CBOE, ni S&P, ni TSX ne soutiennent, ne cautionnent, ne vendent ni ne promeuvent un produit d'investissement basé ou pouvant être basé sur l'indice S&P/TSX 60 VIX.
  
  Exonération de dommage
  EN AUCUN CAS, TMX, SES AFFILIÉES, FOURNISSEURS DE SERVICES, AINSI QUE LEURS DIRIGEANTS, ADMINISTRATEURS, EMPLOYÉS OU MANDATAIRES NE POURRONT ÊTRE TENUS RESPONSABLES DE TOUS DOMMAGES DIRECTS, CONSÉCUTIFS, ACCESSOIRES, INDIRECTS OU SPÉCIAUX DE QUELQUE NATURE QUE CE SOIT OU DE TOUT AUTRE DOMMAGE QUEL QU'IL EN SOIT, Y COMPRIS CEUX DÉCOULANT DE TOUTE DÉCISION PRISE OU D'ACTES POSÉS PAR VOUS SUR LA BASE DE LA CONFIANCE ACCORDÉE AU CONTENU OU RÉSULTANT DE LA PERTE D'UTILISATION, DE DONNÉES OU DE BÉNÉFICES, QUE CES PERTES RÉSULTENT DE L'UTILISATION OU DE L'INCAPACITÉ D'UTILISER TOUT CONTENU DES SITES WEB (OU D'UN SITE LIÉ AUX SITES WEB) OU DE TOUTE AUTRE CAUSE, ET CELA, MÊME SI LE DOMMAGE EST CAUSÉ PAR LA NÉGLIGENCE DE TMX, DE SES AFFILIÉES OU DE SES FOURNISSEURS DE SERVICES, ET MÊME SI L'UN D'ENTRE EUX ÉTAIT INSTRUIT DE LA POSSIBILITÉ QUE PAREILS DOMMAGES SE PRODUISENT.
  
  LES RESTRICTIONS ET EXCLUSIONS SUSMENTIONNÉES S'APPLIQUENT À VOUS DANS TOUTE LA MESURE PERMISE PAR LE DROIT APPLICABLE ET À L'ÉGARD DE TOUTE ACTION DE QUELQUE NATURE QUE CE SOIT, QU'ELLE SOIT FONDÉE SUR LA RESPONSABILITÉ CONTRACTUELLE OU DÉLICTUELLE (Y COMPRIS LA NÉGLIGENCE) OU TOUTE AUTRE THÉORIE EN DROIT OU EN EQUITY. UNE DISPOSITION DÉCLARÉE INVALIDE EST RÉPUTÉE DIVISIBLE ET N'A AUCUNE INCIDENCE SUR LA VALIDITÉ OU LE CARACTÈRE EXÉCUTOIRE DES AUTRES DISPOSITIONS DES PRÉSENTES CONDITIONS D'UTILISATION.
  
  Titres de placement
  Ni TMX, ni ses fournisseurs de services, ni leurs affiliées respectives, ni aucun de leurs dirigeants, administrateurs, employés, mandataires ou détenteurs de licence : a) n'a commenté la valeur d'un titre quelconque mentionné dans le cadre de ces sites ou de tout site lié à celui-ci, b) n'a cautionné ou commandité les titres qui y sont mentionnés, ni c) ne formule ou n'a formulé de recommandations quant à un quelconque titre émis par une des sociétés mentionnées sur les sites Web ou sur tout autre site lié, ou quant à l'opportunité pour une personne en particulier d'investir dans des titres en général. LORSQUE REQUIS, VEUILLEZ OBTENIR L'AVIS DE CONSEILLERS PROFESSIONNELS AU SUJET DE L'ÉVALUATION DE TOUT TITRE, INDICE, RAPPORT, OPINION, CONSEIL OU AUTRE CONTENU.
  
  Publicité et liens
  TMX accepte la publicité de sociétés inscrites, de courtiers et d'autres entités et touche une rémunération pour la publicité affichée sur les sites Web. La présence de cette publicité n'indique ni ne sous-entend aucun cautionnement de la part de TMX.
  
  De plus, par souci de commodité pour nos visiteurs, les sites Web contiennent actuellement certains liens menant à d'autres sites Web. Les procédures et politiques relatives à la protection des renseignements personnels décrites dans le cadre des présentes modalités ne s'appliquent pas à ces sites Web. Nous suggérons que vous communiquez directement avec ces sites Web pour obtenir des renseignements sur leurs politiques relatives à la collecte et à la distribution de données. Si vous décidez de visiter ces sites Web ou une page offerte en lien, vous le faites à vos propres risques. TMX n'est pas responsable de l'exactitude ou de la fiabilité de toute information, toute donnée, toute opinion, tout avis ou toute déclaration affichés sur ces sites. TMX fournit ces liens uniquement par souci de commodité et l'inclusion de ces liens ne signifie pas que TMX cautionne ou accepte une responsabilité quelconque pour le contenu ou l'utilisation de ces sites Web.
  
  Contenu commandité
  Le contenu identifié comme provenant « de nos commanditaires » a été fourni par le commanditaire mentionné dans ce contenu et est offert à des fins d'information seulement. Ce contenu n'est pas cautionné par TMX et TMX n'est pas responsable de, et n'assume aucune responsabilité quant à, toute erreur ou omission dans le contenu fourni, ou toute action entreprise sur la base de ce contenu.
  
  Marques de commerce
  Il est interdit d'utiliser les marques de commerce affichées sur les sites Web (y compris celles énumérées dans la liste ci-dessous, sans toutefois s'y limiter) sans l'autorisation préalable écrite du Groupe TMX ou du tiers qui détient la marque de commerce.
  
  Les marques de commerce suivantes appartiennent à TSX Inc. : The Accumulator, le logo Alberta Stock Exchange, American Venture Exchange, The Asia Pacific Board, The Asian Board, ATX, ATX Access, le logo Bar Chart, le logo Bull and Bear, Canada's Pacific Rim Stock Exchange, Canadian Best Bid and Offer, Canadian Dealing Network, Canadian Unlisted Board, Canadian Venture Exchange, Capital Moves, Capital Pool Company, CARS, CBBO, CDB, CDEX, CDF, CDNX, le logo CDNX, Clarity for Investor Relations, CLS, CPC, CUB, le logo CUB Canadian Unlisted Board Inc., DEX, le logo DEX, le logo DOTS, échangez avec nous, Equities News, Exchange With Us, Experience • Leadership, FOX, Groupe TMX, HIP, INFOCDNX, Infosuite, le logo pastille INSCRITE À LA TSX, Invest with Insight, ir2020, le logo ir2020 Clarity for Investor Relations, LinxPointOne, le logo pastille LISTED ON TSX, Marchés privés TSX, Market at Play, Market Book, Market-by-Order, Market-by-Price, marketdata.tse.com, MarketDepth, MOC, Money Go Round at Stock Market Place, National Enterprise Exchange, NEX, One Success After Another, Public Venture Capital Campaign, S M P, STAMP, Stock Market Place at the TSE, le logo Stock Market Place at the TSE, le logo Stock Market Place Bull & Bear, Taking it to the Street, The Future is Yours to See, This Way Up, TIPS, TIPS 100, TIPS 35, TMX, TMX Argent, TMX Atrium, TMX Datalinx, le logo TMX, TMX Extreme Message Transfer Protocol, TMX Group, TMX International, TMX Money, TMX Powerstream, TMX Quantum, TMX Quantum XA, TMX Quantumfeed, TMX Select, TMXnet, Tomorrow's Stock Exchange, Toronto 35 Index, Toronto Stock Exchange, Trade Your Way, TRADECDNX, TSE, TSE 100 Index, TSE 200 Index, TSE 300 Composite Index, le logo TSE CDNX, le logo TSE, le logo TSE Edge, le logo TSE Securities World, TSX, TSX Alternative Trade eXecution, TSX Block List Leaders, TSX Compliance Alerts Reporting System, TSX Datalinx, le logo TSX, TSX Direct, le logo TSX discovery, TSX Firm Order eXecution, TSX Group, TSX Historical Trading Data, TSX IE, TSX Infinity, TSX Intelligence Engine, le logo TSX Intelligence Engine, le logo TSX investinit, TSX Market On Close, TSX Market Sense, TSX Markets, TSX NAVex, TSX Network Resources Program et son logo, TSX Private Markets, TSX Quantum, TSX Quantum Revolution, TSX Quantum the Speed of Trade et son logo, TSX Quantum la Vitesse de Négociation et son logo, TSX QuantumFeed, TSX SecureFile, TSX Technologies, TSX Venture 50, le logo TSX Venture 50, TSX Venture Exchange, TSXconnect, TSXPress, TSXV, TSXV LiquidityPro, Voir le futur. Réaliser l'avenir, Waggle, Where the World Trades Canada, XMT, Your Key to Capital.
  
  Les marques de commerce et autres marques suivantes appartiennent à Bourse de Montréal Inc. et elles sont utilisées sous licence : Analyste attitré en instruments dérivés (AAID); BAX; Bourse canadienne de contrats à terme et options; Bourse canadienne de produits dérivés; Bourse canadienne d'options; les logos Bourse de Montréal; Bourse Verte Canadienne; Bourse Verte de Montréal; CADC; Canadian Annual Derivatives Conference; Canadian Derivatives Exchange; Canadian Futures and Options Exchange; Canadian Green Exchange; Canadian Options Exchange; CAREX; CAREX Marché Canadien de Ressources; CAREX Canadian Resources Exchange; CCAD; CDCS; Certified Derivatives Analyst (CDA); CGB; CGF; CGZ; CIFO; Compensation sur mesure; Conférence canadienne annuelle des dérivés; Converge; le logo Converge; Converge Compensation sur mesure et son logo; Customized Clearing; Converge Customized Clearing et son logo; Derivatives Institute; DTM; FIG; Institut des dérivés; LGB; Logo Dessin étoile / Star Design; MAX, Electronic Trading System for Options; MAX, Système de négociation électronique pour les options; MCWX; MIO; Montreal Automated System (SAM); Montreal Green Exchange; Montreal-By-Price; MPCX; MX; OBW; OBX; OBY; OBZ; OGB; ONX; OIS-MX; SAM; le logo SAM Montreal Automated System; SCF; SOLA; le logo SOLA; SXA; SXB; SXF; SXH; SXM; SXO; SXY; Système automatisé de Montréal; USX; WCH; WCZ; XCB : Indice bancaire canadien; XCB : The Canadian Banking Index; XCF : Indice canadien des produits forestiers; XCF : The Canadian Forest Products Index; XCI: Indice canadien des biens d'équipement; XCI : The Canadian Industrial Products Index; XCM : Indice canadien des mines et métaux; XCM : The Canadian Mining and Minerals Index; XCO : Indice canadien des hydrocarbures; XCO : The Canadian Oil and Gas Index; XCU : Indice canadien des services publics; XCU : The Canadian Utilities Index; XXM : Indice canadien du marché; XXM : The Canadian Market Portfolio Index; WCH.
  
  AgriClear, le logo Agriclear et AgriClear Direct sont les marques de commerce d'Agriclear Limited Partnership, commanditée par Agriclear Inc., et elles sont utilisées sous licence.
  
  Alpha Group, Alpha Exchange, Alpha Intraspread, Alpha Main, Alpha Venture Plus, Alpha X, Alpha et son logo, Dark Match Facility, Dark Order, Intraspread Facility, SDL, Seek Dark Liquidity, Trade Up et son logo, sont les marques de commerce d'Alpha Trading Systems Limited Partnership et elles sont utilisées sous licence.
  
  Boston Options Exchange, et le logo BOX Options Exchange sont des marques de commerce de Boston Options Exchange Group, LLC et elles sont utilisées sous licence.
  
  CDS et CDSX sont les marques de commerce de La Caisse canadienne de dépôt de valeurs limitée et elles sont utilisées sous licence.
  
  CCCPD, les logos CCCPD et CDCC, CDCC et CDCS sont les marques de commerce de Corporation canadienne de compensation de produits dérivés et Canadian Derivatives Clearing Corporation et elles sont utilisées sous licence.
  
  Shorcan et Shorcan Brokers sont les marques de commerce de Shorcan Brokers Limited et elles sont utilisées sous licence.
  
  Les marques de commerce ci-dessous appartiennent aux fournisseurs d'information de Groupe TMX :
  CanDeal et le logo CanDeal sont des marques déposées de CanDeal.ca Inc. et elles sont utilisées sous licence.
  
  CNW est une marque déposée de Groupe CNW Ltée et elle est utilisée sous licence.
  
  ICE est une marque de commerce d'IntercontentalExchange Inc. et elle est utilisée sous licence.
  
  iShares est une marque de commerce de Barclays Global Investors, N.A.
  
  ROGERS, CANADIAN BUSINESS, PROFIT et leurs logos respectifs sont des marques de commerce de Rogers Publishing Limited et ne peuvent pas être utilisées sans la permission du propriétaire. Le contenu des publications énumérées est protégé par droit d'auteur et ne peut être copié ni utilisé à d'autres fins qu'à titre de référence personnelle sans avoir obtenu au préalable l'autorisation écrite de Rogers Publishing Limited.
  
  Quotemedia et le logo Quotemedia sont des marques de commerce de Quotemedia, Inc. et elles sont utilisées sous licence.
  
  L'indice composé S&P/TSX, l'indice composé S&P/TSX de croissance et les autres indices S&P/TSX sont des produits de S&P Dow Jones Indices LLC (« SPDJI ») et de TSX Inc. (« TSX »). Standard & Poor'sMD et S&PMD sont des marques déposées de Standard & Poor's Financial Services LLC (« S&P »), Dow JonesMD est une marque déposée de Dow Jones Trademark Holdings LLC (« Dow Jones ») et TSXMD est une marque déposée de TSX. SPDJI, Dow Jones, S&P et TSX ne soutiennent, ne cautionnent, ne vendent, ni ne promeuvent aucun produit fondé sur les indices S&P/TSX, ne font aucune déclaration quant au bien-fondé d'un placement dans un tel produit et ne peuvent être tenues responsables d'erreurs, d'omissions ou d'interruptions touchant les indices S&P/TSX ou les données y afférentes.
  
  Hyperliens
  À moins que vous n'ayez conclu un accord écrit avec TMX énonçant des modalités différentes, vous pouvez fournir un lien hypertexte vers les sites Web à partir d'un autre site Web seulement aux conditions suivantes : a) le lien est un lien textuel qui indique clairement « Page d'accueil du Groupe TMX » ou « Page d'accueil de TMXargent »; b) le lien est établi avec l'adresse suivante (y mène directement l'utilisateur) : https://www.tmx.com (dans le cas de la page d'accueil du Groupe TMX) ou l'adresse https://money.tmx.com (dans le cas de la page d'accueil de TMXargent) et non pas avec les adresses menant à d'autres pages des sites Web; c) l'apparence, la position et les autres aspects relatifs au lien ne sont pas tels qu'ils endommagent ou diluent la cote d'estime associée au nom et aux marques de commerce de TMX; d) l'apparence, la position et les autres aspects relatifs au lien ne créent pas l'impression trompeuse qu'une entité est associée à TMX ou commanditée par cette dernière; e) le lien, lorsqu'il est activé par un utilisateur, fait afficher, plein écran, le site de TMX et non pas une « boîte » dans le cadre du site Web sur lequel se trouve le lien; f) TMX se réserve le droit, en tout temps et à son entière discrétion, de résilier immédiatement son consentement à ce que vous établissiez un lien avec ses sites Web.
  
  Aucun lien en direction ou en provenance de contenu fourni par des fournisseurs de services ne peut être créé sans l’autorisation écrite préalable des fournisseurs de services en question.
  
  Utilisation non confidentielle de vos commentaires
  Tout commentaire, toute communication non personnelle, toute idée ou tout matériel que vous affichez ou que vous transmettez à TMX est, et sera traité comme étant non confidentiel et non exclusif. En transmettant ou en affichant toute forme de communication ou matériel sur les sites Web, vous accordez à TMX et à ses filiales un accès non restreint, une licence d'utilisation irrévocable lui permettant d’utiliser, de reproduire, d'afficher, de modifier, de transmettre, de distribuer, de publier ou de diffuser votre communication à toutes fins. Vous octroyez aussi à TMX le droit d'utiliser tout concept, idée, savoir-faire ou technique que vous lui avez envoyé à toutes fins. Cependant, nous n'allons pas émettre votre nom ou publier le fait que vous nous avez soumis du matériel ou tout autre renseignement sauf si : (a) vous nous donnez la permission de le faire, (b) nous vous avisons que le matériel ou tout autre renseignement que vous avez soumis à une section particulière du site sera publiée ou d'une quelconque autre façon utilisée avec votre nom, ou (c) nous sommes juridiquement requis de le faire.
  
  Si vous accédez ou participez au blogue de la Bourse, veuillez revoir les conditions d'utilisation du blogue avant de lire ou d’afficher des commentaires sur ce blogue.
  
  Protection des renseignements
  Des mesures de sécurité raisonnables assurent une protection contre la perte de l’information sur laquelle nous exerçons un contrôle et son mauvais usage ou son interception par des tiers. Toutefois, il n’est pas encore possible d’assurer la confidentialité et la sécurité totales de l’information sur Internet. Nous n’assumons aucune responsabilité pour les dommages que vous pourriez subir en raison de la perte, de l’interception, de la modification ou du mauvais usage de l’information que vous nous fournissez ou de l’information transmise par Internet. Veuillez consulter notre Politique de confidentialité pour plus de détails.
  
  Changements des conditions d'utilisation
  TMX se réserve le droit de modifier sans préavis les présentes conditions d'utilisation en tout temps. Vous êtes liés par de telles révisions, et nous vous encourageons à visiter cette page fréquemment pour vous tenir au courant.
  
  Modification au site Web
  TMX peut apporter des modifications aux sites Web, incluant la suppression ou la discontinuation de tout contenu sur ou disponible par l'entremise des sites Web, en tout temps et à sa seule discrétion.
  
  Violation des conditions d'utilisation
  TMX se réserve le droit d'exercer tous les recours judiciaires et en droit disponibles en cas de violation des présentes conditions d'utilisation, y compris celui d'empêcher l'accès à notre site à partir d'une adresse Internet en particulier.
  
  Autres pays
  Il est possible d'accéder aux sites Web à partir de pays du monde entier autres que le Canada, et les sites pourraient contenir des références à des produits, à des services ou à des programmes de TMX qui n'ont pas été publiés dans votre pays. Ces références ne supposent pas que TMX entend publier ces produits, services ou programmes dans votre pays. TMX ne fait aucune déclaration selon laquelle le contenu des sites Web est approprié ou peut être utilisé à d'autres endroits, et y accéder à partir de territoires où son contenu est illégal est interdit. Ceux qui choisissent d'accéder aux sites Web à partir d'autres endroits le font de leur propre initiative et à leur propre risque; il leur incombe de se conformer à toutes les lois locales.
  
  Lois applicables
  Les sites Web (à l'exclusion des sites interconnectés) sont contrôlés par TMX à partir de ses bureaux situés dans la province d'Ontario, au Canada. En accédant aux sites Web, vous convenez avec TMX que toute question relative à l'accès ou à l'utilisation des sites Web devra être interprétée et régie en vertu, selon le cas, des lois en vigueur dans la province d'Ontario ou des lois fédérales du Canada, sans tenir compte de leurs règles en matière de conflits de lois. TMX et vous convenez également, par les présentes, de vous soumettre à la compétence exclusive des tribunaux de la province d'Ontario dans le cadre de toute question liée aux présentes conditions d'utilisation.
  
  Pour nous joindre
  Pour toute question concernant les présentes conditions d’utilisation ou les sites Web, veuillez communiquer avec nous à l’adresse courriel webmaster@tmx.com.
  
  VOUS RECONNAISSEZ QUE VOUS AVEZ LU LES PRÉSENTES CONDITIONS D’UTILISATION, QUE VOUS LES COMPRENEZ ET QUE VOUS ACCEPTEZ D’ÊTRE LIÉ PAR TOUTES LEURS MODALITÉS.
  
  Relations avec les investisseurs et questions connexes
  Information prospective
  Les sites Web renferment de l'« information prospective » (au sens attribué à ce terme dans la législation en valeurs mobilières canadienne applicable) qui est fondée sur des attentes, des hypothèses, des estimations, des prévisions et d'autres facteurs que la direction croit pertinents en date de leur publication. On reconnaît souvent, mais pas toujours, l’information prospective à l’emploi de termes et d’expressions de nature prospective comme « prévoir », « s’attendre à », « budgéter », « planifier », « viser », « estimer », « avoir l’intention de », ou « croire », ou des variantes de ces termes et expressions ou leur forme négative ou des déclarations selon lesquelles certaines mesures ou certains événements ou résultats « peuvent », « devraient », « pourraient » ou « pourront », ou non, être prises, survenir ou se matérialiser. De par sa nature, l’information prospective exige que nous formulions des hypothèses et est exposée à des risques et à des incertitudes d’importance en raison desquels nos attentes, nos conclusions et nos hypothèses pourraient se révéler inexactes.
  
  À titre d'exemple, l'information prospective peut comprendre, sans s'y limiter, les facteurs relatifs aux Bourses de titres, de dérivés et aux contrats énergétiques ainsi qu'aux chambres de compensation et à l'entreprise, aux objectifs stratégiques et aux priorités, aux conditions du marché, aux cours, à la technologie proposée et aux autres initiatives, conditions financières, activités et perspectives du Groupe TMX, qui comportent des risques et des incertitudes d'importance. Ces risques incluent la concurrence d'autres Bourses ou marchés, y compris les systèmes de négociation parallèles et les nouvelles technologies, à l'échelle nationale et internationale; la dépendance à l'égard de l'économie canadienne; l'incidence défavorable de l'incertitude économique mondiale sur nos résultats; l'incapacité de recruter et de maintenir en poste du personnel qualifié; des facteurs géopolitiques et autres qui pourraient entraîner une interruption des activités; la dépendance à l'égard de la technologie de l'information; la vulnérabilité de nos réseaux et des tiers fournisseurs de services à l'égard des risques liés à la sécurité; l'incapacité de mettre en œuvre nos stratégies; les contraintes d'ordre réglementaire; les risques de litiges; la dépendance à l'égard d'un nombre suffisant de clients; l'incapacité d'élaborer ou de faire accepter de nouveaux produits; l'incidence défavorable de nouvelles activités commerciales; l'incapacité de satisfaire nos besoins de trésorerie en raison de notre structure de société de portefeuille et des restrictions relatives au versement de dividendes; la dépendance et les restrictions imposées par des accords de licence et d'autres arrangements; la dépendance des activités de négociation à l'égard d'un petit nombre de clients; les nouvelles technologies permettant de diffuser facilement l'information nous appartenant; les risques liés aux activités de compensation; les défis posés par l'expansion internationale; les restrictions applicables à la propriété des actions du Groupe TMX; l'incapacité à protéger notre propriété intellectuelle; la dépendance envers de tiers fournisseurs; l'incidence défavorable d'un événement de marché systémique sur notre secteur des dérivés; les risques liés au crédit de clients; le fait que les structures de coûts sont largement fixes; les risques liés à l'intégration des activités, des systèmes et du personnel des activités nouvellement acquises; et la dépendance à l'égard du niveau d'activité boursière, qui échappe complètement à notre volonté. Les réalisations et résultats réels différeront vraisemblablement, voire sensiblement, de ceux présentés explicitement ou implicitement par l'information prospective contenue dans les sites Web.
  
  Cette information prospective est fondée sur un certain nombre d'hypothèses qui peuvent se révéler inexactes, y compris, mais sans s'y limiter, les hypothèses concernant la capacité du Groupe TMX à soutenir la concurrence de Bourses mondiales et régionales; la conjoncture économique et commerciale en général; les taux de change (y compris les estimations du taux de change entre le dollar américain et le dollar canadien); le niveau des opérations et de l'activité sur les marchés et particulièrement le niveau des opérations sur les principaux produits du Groupe TMX; la disponibilité continue de financement à des conditions acceptables pour des projets futurs; la productivité du Groupe TMX, de même que celle de ses concurrents; la concurrence sur le marché; les activités de recherche et développement; la capacité de lancer avec succès de nouveaux produits de dérivés et de capital-actions; les avantages fiscaux et les modifications fiscales; l'incidence de divers règlements sur le Groupe TMX et sur ses clients; le maintien de bonnes relations entre le Groupe TMX et ses employés et la durée de toute interruption de travail, panne d'équipement ou autre interruption importante des activités à l'une de ses exploitations, à l'exception des interruptions pour entretien et autres interruptions similaires prévues.
  
  Bien que nous estimions que des événements ou des faits nouveaux pourraient nous amener à modifier notre point de vue, nous n'avons aucunement l'intention de mettre à jour la présente information prospective, à moins que la législation en valeurs mobilières applicable ne nous y oblige. On ne doit pas se fier à la présente information prospective comme s'il s'agissait de notre avis à toute date postérieure à la date de chacune des pages individuelles du contenu ou des documents inclus dans ces sites Web. Nous avons tenté de répertorier les facteurs importants susceptibles de faire différer sensiblement les mesures, événements ou résultats réels de ceux qui sont actuellement présentés dans l'information prospective. Toutefois, il peut exister d'autres facteurs pouvant faire différer sensiblement les mesures, événements ou résultats de ceux qui sont actuellement attendus. Rien ne garantit que l'information prospective se révélera exacte, étant donné que les résultats réels et les événements futurs pourraient différer sensiblement de ceux prévus dans ces énoncés. Par conséquent, le lecteur ne doit pas se fier outre mesure à l'information prospective. Les facteurs énoncés ci-dessus ne représentent pas la liste exhaustive des facteurs pouvant avoir une incidence sur notre entreprise. La rubrique Risques et incertitudes de notre plus récent rapport de gestion annuel contient une description des facteurs de risque susmentionnés.
  
  Information sur les relations avec les investisseurs
  L'information affichée dans la section des relations avec les investisseurs des sites Web est mise à jour par le chef des services financiers du Groupe TMX. Toute l'information affichée dans la section des relations avec les investisseurs des sites était exacte au moment de l'affichage, mais peut être annulée par des divulgations ultérieures du Groupe TMX. Le Groupe TMX n'assume aucune obligation de divulgation au-delà de ce qui est requis par la loi. Pour connaître les documents officiels d'information des investisseurs du Groupe TMX, veuillez consulter les dépôts de documents du Groupe TMX auprès des organismes de réglementation canadiens des valeurs mobilières à l'adresse www.sedar.com.</p>
        </div>
    )
}

export default Conditions
